# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'TexpeechIos' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for TexpeechIos

  
  target 'TexpeechIos-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

    pod 'RNSound', :path => '../node_modules/react-native-sound'

  end

  target 'TexpeechIosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'Firebase/Core', '~> 5.3.0'
pod 'Firebase/Database'