# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'TexpeechIos' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for TexpeechIos

  
  target 'TexpeechIos-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TexpeechIosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'Firebase/Core'
pod 'Firebase/Database'